### ISSUE TITLE
Freeze N first cards on climb

### ISSUE THREAD

**Issue by aember** [andor9/tyrant_optimize#14]
Hey! I have a suggestion. Addition of a flag 
-f N
which causes the optimizer to freeze the first N cards of My Deck while normally climbing the rest. 
Allows for e.g.:
- optimization of the suboptimal first drop,
- making the climb faster when the first drops are obvious.

No idea how hard it is to code that, so I'm filing it here for someone knowledgeable to assess.

Thanks,
aember

**Comment by andor9** [comment]
good idea. thank you. will think of it.

**Comment by andor9** [comment]
Add flag freeze N in v2.5.2. Thank you.
