### ISSUE TITLE
Simple TUO GUI doesn't update raids.xml

### ISSUE THREAD

**Issue by tehaaron** [andor9/tyrant_optimize#17]
The "Update XMLs" button on the SimpleTUOptimizeStarter.exe GUI does not update the raids.xml file.

**Comment by BloodKi1** [comment]
It never has to my knowledge.  Raids.xml usually comes with new releases, but im assuming as there were no new skills this raid andor did not release a new update.

It can be easily fixed however by editing your raids.xml file.

Once you have  raids.xml opened inside an editor, simply copy/paste an old raid.  (Or just replace the values in it)

For example it would now become

-id.4-id.
-name.Oluth-name.
-commander.1545-commander.

*replace - with < 
And
. With >
(Wont show if I type it out correctly  -.-)
Etc...

*Also you would need to replace card values... for this raid they were

12294, 12304, 12314, 12324, 12334

**Comment by tehaaron** [comment]
I realize how easy it is to edit an xml document. For previous raids Andor has also happened to make a new release for various reasons (new skills, updated mechanic, etc) that included the new raids.xml. I believe this was the first raid without such an update and since many people just pull down the release zip they didn't get the newest raids.xml. These same people are likely not very familiar with github and tend to use the button in the simple GUI to get what they believe are the latest xml files.

Consider this a feature request then. Thanks.

**Comment by andor9** [comment]
Already done for a while. Thank you.
Closing the issue.
