### ISSUE TITLE
Make instructions

### ISSUE THREAD

**Issue by sslotsky** [andor9/tyrant_optimize#19]
I'd like to clone the repo and run TUO from there, so that I can do `git pull` and `make` to update rather than downloading from the web.

In my c/c++ days we used to run 

```
./configure
make
sudo make install
```

But this does not work on my Ubuntu box. There appears to be no config, and running `make` gives me:

```
g++ -Wall -Werror -std=gnu++11 -O3 -DNDEBUG -o obj/cards.o -c cards.cpp
cards.cpp:3:31: fatal error: boost/tokenizer.hpp: No such file or directory
 #include <boost/tokenizer.hpp>
                               ^
compilation terminated.
make: *** [obj/cards.o] Error 1
```

Would it be possible to get `make` instructions in the README?

**Comment by jamestombs** [comment]
You need to download the c++ boost library for your respective OS.
