### ISSUE TITLE
Overload bug

### ISSUE THREAD

**Issue by technophile77** [andor9/tyrant_optimize#20]
Overload is being applied to units with Jam, even when jam is not ready to go off. This never happens in the game. Example, on turn 7 Dune Runner Jams the Sculpted Aegis, and then on turn 9 still gets overload. I believe this issue is causing overload to be undervalued when combined with jam. 
$ ./tuodebug.exe "Daedalus, Dune Runner" "Halcyon, Sculpted Aegis" debug
Warning: Ignore unknown skill [evolve] in data/cards.xml
Your Deck: Deck: APhBGs
Daedalus, Dune Runner
Enemy's Deck:1: Deck: EAhHEk
## Halcyon, Sculpted Aegis

TURN 1 begins for Commander [Daedalus hp:47]
Commander [Daedalus hp:47] plays Assault 0 [Dune Runner: 5/17/1 imperial, Valor 5, Jam every 4, Berserk 2]
## TURN 1 ends for Commander [Daedalus hp:47]

TURN 2 begins for Commander [Halcyon hp:47]
Commander [Halcyon hp:47] plays Assault 0 [Sculpted Aegis: 4/20/3 imperial, Evade 2, Armor 5, Heal all 4]
Commander [Halcyon hp:47] Enhance Armor 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:3]
Commander [Halcyon hp:47] Strike 2 on Assault 0 [Dune Runner att:5 hp:17 cd:1]
## TURN 2 ends for Commander [Halcyon hp:47]

TURN 3 begins for Commander [Daedalus hp:47]
Assault 0 [Dune Runner att:5 hp:15 cd:1] reduces its timer
Assault 0 [Dune Runner att:5 hp:15] loses Valor (weak blocker Assault 0 [Sculpted Aegis att:4 hp:20 cd:3])
Commander [Daedalus hp:47] Enhance Berserk 1 on Assault 0 [Dune Runner att:5 hp:15]
Commander [Daedalus hp:47] Overload on Assault 0 [Dune Runner att:5 hp:15]
Commander [Daedalus hp:47] Strike 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:3] but it evades
Assault 0 [Dune Runner att:5 hp:15, overloaded] attacks Assault 0 [Sculpted Aegis att:4 hp:20 cd:3] for 5-[6(armor)]=0 damage
## TURN 3 ends for Commander [Daedalus hp:47]

TURN 4 begins for Commander [Halcyon hp:47]
Assault 0 [Sculpted Aegis att:4 hp:20 cd:3] reduces its timer
Commander [Halcyon hp:47] Enhance Armor 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:2]
Commander [Halcyon hp:47] Strike 2 on Assault 0 [Dune Runner att:5 hp:15]
## TURN 4 ends for Commander [Halcyon hp:47]

TURN 5 begins for Commander [Daedalus hp:47]
Commander [Daedalus hp:47] Enhance Berserk 1 on Assault 0 [Dune Runner att:5 hp:13]
Commander [Daedalus hp:47] Overload on Assault 0 [Dune Runner att:5 hp:13]
Commander [Daedalus hp:47] Strike 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:2] but it evades
Assault 0 [Dune Runner att:5 hp:13, overloaded] attacks Assault 0 [Sculpted Aegis att:4 hp:20 cd:2] for 5-[6(armor)]=0 damage
## TURN 5 ends for Commander [Daedalus hp:47]

TURN 6 begins for Commander [Halcyon hp:47]
Assault 0 [Sculpted Aegis att:4 hp:20 cd:2] reduces its timer
Commander [Halcyon hp:47] Enhance Armor 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:1]
Commander [Halcyon hp:47] Strike 2 on Assault 0 [Dune Runner att:5 hp:13]
## TURN 6 ends for Commander [Halcyon hp:47]

TURN 7 begins for Commander [Daedalus hp:47]
Commander [Daedalus hp:47] Enhance Berserk 1 on Assault 0 [Dune Runner att:5 hp:11]
Commander [Daedalus hp:47] Overload on Assault 0 [Dune Runner att:5 hp:11]
Commander [Daedalus hp:47] Strike 1 on Assault 0 [Sculpted Aegis att:4 hp:20 cd:1] but it evades
Assault 0 [Dune Runner att:5 hp:11, overloaded] Jam on Assault 0 [Sculpted Aegis att:4 hp:20 cd:1]
Assault 0 [Dune Runner att:5 hp:11, overloaded] attacks Assault 0 [Sculpted Aegis att:4 hp:20 cd:1, jammed] for 5-[6(armor)]=0 damage
## TURN 7 ends for Commander [Daedalus hp:47]

TURN 8 begins for Commander [Halcyon hp:47]
Assault 0 [Sculpted Aegis att:4 hp:20 cd:1, jammed] reduces its timer
Commander [Halcyon hp:47] Enhance Armor 1 on Assault 0 [Sculpted Aegis att:4 hp:20, jammed]
Commander [Halcyon hp:47] Strike 2 on Assault 0 [Dune Runner att:5 hp:11]
## TURN 8 ends for Commander [Halcyon hp:47]

TURN 9 begins for Commander [Daedalus hp:47]
Commander [Daedalus hp:47] Enhance Berserk 1 on Assault 0 [Dune Runner att:5 hp:9]
Commander [Daedalus hp:47] Overload on Assault 0 [Dune Runner att:5 hp:9]
Commander [Daedalus hp:47] Strike 1 on Assault 0 [Sculpted Aegis att:4 hp:20] but it evades
Assault 0 [Dune Runner att:5 hp:9, overloaded] attacks Assault 0 [Sculpted Aegis att:4 hp:20] for 5-[6(armor)]=0 damage
TURN 9 ends for Commander [Daedalus hp:47]

**Comment by andor9** [comment]
Fixed. Thank you.
