### ISSUE TITLE
Flag 'fund' does not optimize

### ISSUE THREAD

**Issue by martin53757** [andor9/tyrant_optimize#28]
Just discovered the great feature 'fund'. I love it!

Tried it but got a weired result: 
Used 'fund 750' (tuo "_Excelsitus Mutant-5" "Excelsitus Mutant-5" pvp random fund 750 climb 10000000) and got the advice to upgrade nexor for 550 SP and a increased in score of 0.7 percentage points. 
When I use 'fund 500' (tuo "_Excelsitus Mutant-5" "Excelsitus Mutant-5" pvp random fund 500 climb 10000000) I get as the result to upgrade Baughe for 275 SP and a plus of 2 percentage points. 

Is it a bug or intended behaviour?

**Comment by andor9** [comment]
Thanks.
Generally it's because of the RNG, sort of intentionally for diversity.
For your case, there is a limitation that the commander chosen by RNG greatly impact the subsequent climbing. Still some space to improve but I have no clear idea yet.
