### ISSUE TITLE
Identify TUO version in log and Simple UI

### ISSUE THREAD

**Issue by aember** [andor9/tyrant_optimize#29]
Not showing the current release anywhere (except running the executable with no parameters) makes it harder to diagnose people's problems and harder for them to notice they are using obsolete version (done that too many times myself).

Proposal: 
show the release version ID in any or all of the following:
1) console output
2) Simple UI title bar
3) name of the executable (perhaps not - problems when updating, old file won't be overwritten)

Thanks!

**Comment by andor9** [comment]
Thanks. It's on the Simple UI title bar now.
