### ISSUE TITLE
Infection in files ?

### ISSUE THREAD

**Issue by themacboy** [andor9/tyrant_optimize#30]
With the last version 2.7.2 Avast anti-virus alert me that the file contains a infection:

Win32:Evo-gen [Susp]

**Comment by jamestombs** [comment]
Looks like the file is fine: https://www.virustotal.com/uk/file/b0936820f00e458ef8f468544db69fa64f1cc628cf4a5fae1cba27f510cca1c1/analysis/1429651292/

**Comment by themacboy** [comment]
Then why the KB increase, the changes don't look really great to justify it.
