### ISSUE TITLE
2.7.2 Error

### ISSUE THREAD

**Issue by Gurubabzen** [andor9/tyrant_optimize#31]
Hey there Andor. First of all love your work.

My problem is that since i upgraded to 2.7.2 i cant get the sim to work.

I use the GUI and whenever i press the simulate, my CMD opens but closes again to fast to read anything.

I have made sure that all of my inputs are correct.

Hope to see this fixed, as i love the tool.

**Comment by andor9** [comment]
Please try tuo.2.7.2-x86.zip.
