### ISSUE TITLE
V2.9.1 Campaign sims + VIP failing

### ISSUE THREAD

**Issue by OniZakuma** [andor9/tyrant_optimize#33]
Running a command like:

tuo.exe "Maion-1, Obsidian, Stoneheart, Dreamhaunter, Sensor Storm, Tazerious, Elite Squadron, Serraco Sire, High Constable" "Deidon Heroic 6" campaign ordered vip "Maion-1, Obsidian, Stoneheart, Dreamhaunter, Sensor Storm, Tazerious, Elite Squadron, Serraco Sire, High Constable" -c endgame 1 -t 3 -o=./data/ownedcardsXYZ.txt climb 20

causes the following error:

terminate called after throwing an instance of 'boost::exception_detail::clone_i
mplboost::exception_detail::error_info_injector<std::domain_error >'
  what():  Error in function boost::math::binomial_distribution<d>::find_upper_b
ound_on_p: Number of Successes argument is 2.1000000000000001, but must be <= Nu
mber of Trials !

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by andor9** [comment]
Thank you. Fixed in v2.9.2.
